// IN THE CONTEXT OF A PUBLISHED PACKAGE, OK!!?!?!
exports.uselessFiles = [
  '.babel.config.js',
  '.babelrc',
  '.drone.yml',
  '.editorconfig',
  '.eslintignore',
  '.eslintrc-ts.js',
  '.eslintrc-ts',
  '.eslintrc',
  '.gitignore',
  '.nyc_output',
  '.prettierrc',
  '.stylelintignore',
  '.stylelintrc.json',
  '.stylelintrc',
  '.travis.yaml',
  '.travis.yml',
  'babel.config.js',
  'coverage',
  'gulpfile.js',
  'lcov-report',
  'lerna.json',
  'now.json',
  'postcss.config.js',
  'tsconfig.json',
]
