// USELESS IN THE CONTEXT OF A _PUBLISHED_ PACKAGE, OK!!?!?!
// THEY'RE NOT USELESS. PLEASE DONT TAKE OFFENSE,
// I LOVE ALL YOUR ESLINT CONFIGS, CODE COVERAGE AND WHATNOT <3
exports.uselessFiles = [
  '.babel.config.js',
  '.babelrc',
  '.drone.yml',
  '.editorconfig',
  '.eslintignore',
  '.eslintrc-ts.js',
  '.eslintrc-ts',
  '.eslintrc',
  '.gitignore',
  '.github',
  '.nyc_output',
  '.prettierrc',
  '.stylelintignore',
  '.stylelintrc.json',
  '.stylelintrc',
  '.travis.yaml',
  '.travis.yml',
  'babel.config.js',
  'coverage',
  'gulpfile.js',
  'lcov-report',
  'lerna.json',
  'now.json',
  'vercel.json',
  'netlify.toml',
  'postcss.config.js',
  'tsconfig.json',
]
